### PR TITLE
Upgrade to Jest 27

### PR DESCRIPTION
**Pull request by nickmccurdy**
**What**: Upgrade to Jest 27

**Why**: Ensuring compatibility with breaking changes in Jest 27

**How**: Upgrading packages and manually setting `testEnvironment` to `jsdom`

**Checklist**:

- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by nickmccurdy** [comment]
What's the CI error? Do we need to use npm 7 in ci since I used it to update `package-lock.json`?

**Comment by nickmccurdy** [comment]
The Cypress startup failure seems to be unrelated, it shouldn't even be using Jest.

**Comment by smeijer** [comment]
Does it help if you install the update using npm 6? Worth a shot?

**Comment by nickmccurdy** [comment]
I already fixed that issue by using npm 6. The Cypress issue seems to be unrelated.

**Comment by ladykraken** [comment]
gh repo clone testing-library/testing-playground

**Pull request closed without merging**
