### PR TITLE
feat: make extension build scripts firefox compatible

### PR DESCRIPTION
**Pull request by WeslleyNasRocha**
**What**: Adding support for Firefox extensions

**Why**: So people who use Firefox can use this extension

**How**: Adding the [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) package, we can run and build the extension in firefox

**Checklist**:

- [x] Tests
- [x] Ready to be merged
      

It is ready to run:
1. In project root, execute `build:devtools:firefox`
2. Then on firefox, go to `about:debugging#/runtime/this-firefox`
3. Click on **Load temporary add-on** 
image
4. Select the `.zip` file from `<project_root>/dist/` folder and click **open**
image
5. There is 2 warnings about the manifest.json, but testing it out, it works
image

Peek 13-01-2021 14-53

### CODE REVIEW

**Comment by NeekSandhu** [comment]
Are you able to run it in Firefox without having to upgrade to version 3.x.x of `crx-bridge`?!

**Comment by calvellido** [comment]
Tested on Firefox Developer Edition 85.0b9 (64-bit) and working like a charm, thanks!!

**Comment by calvellido** [comment]
It's also working in my standard Firefox 84.0.2 (64-bit)

**Comment by WeslleyNasRocha** [comment]
> Are you able to run it in Firefox without having to upgrade to version 3.x.x of `crx-bridge`?!

Yes, my guess is that `web-ext` is doing some sort of conversion under the hood, cause i didn't  even need to change `chrome.devtools` to `browser.devetools`

**Comment by WeslleyNasRocha** [comment]
I can upload this to firefox store and transfer to you the right later?

**Comment by smeijer** [comment]
I'll take a look at this tomorrow and come back to you 😊.

Thanks for the work you've done. Much appreciated!

**Comment by smeijer** [comment]
Thanks again! The changes are looking good! I'll try get the thing published asap.

**Comment by smeijer** [comment]
Ok. This process was a lot simpler than for the Chrome Store, although, Mozilla asks to upload the source code, while Google didn't do that.

Anyways, the extension has been submitted, and is "Awaiting Review". :tada:

**Comment by smeijer** [comment]
Still waiting 

Screenshot_20210129-213809

**Comment by WeslleyNasRocha** [comment]
> Still waiting
> 
> Screenshot_20210129-213809

Looks like they are verifying every new extension that come in

**Comment by WeslleyNasRocha** [comment]
@smeijer 
> Still waiting
> 

Anything yet?

**Comment by smeijer** [comment]
Yeah, bad news. I'm afraid I have to stop trying. I've submitted three versions now. 

The first time, it was automatically rejected because I missed the question: _let me know from which add-on version you've forked this listing._ that they asked in the "developer hub".

The second time, they couldn't get it running due to some NPM issues

```
🚨 Build failed.
@parcel/transformer-postcss: Could not resolve package "postcss" that satisfies ^8.2.1. Found 7.0.35
```

The third time, they mention _the resulting code is different from the one in the final xpi._

I don't know what else to do.

**Comment by WeslleyNasRocha** [comment]
I've tried to upload it on zip format and they accepted 😕 

I'm gonna add you as a owner too

https://addons.mozilla.org/pt-BR/firefox/addon/testing-playground/

**Comment by smeijer** [comment]
Thanks! You can add `stephan.meijer@gmail.com` while I go cry in a corner. Much appreciated! But their review process... Why?

**Comment by smeijer** [comment]
I see that you've added me. Thanks! Also for submitting. I think it depends on the reviewer. You had a different reviewer, whom accepted in 2 days without questions asked 😅.

Thanks again. Much, much, appreciated.

**Comment by WeslleyNasRocha** [comment]
Hahaha, don't even i know, i just submitted and got accepted right away.

**Comment by smeijer** [comment]
@WeslleyNasRocha , I've published a new version of the Chrome Extension, to fix a bug regarding conflicting query suggestions.

Can you publish a new version for Firefox? I'm a bit hesitant to do it myself :sweat_smile:

**Pull request merged**
