### PR TITLE
chore: add issue templates

### LINKED ISSUE #125: add a issue and pr template
We should have some templates here.

Issues:
- should have a link to a playground in case there is a behavior bug
- a hint to check if the bug also exists on http://develop.testing-playground.com/

Pull requests:
 - ?

### PR DESCRIPTION
**Pull request by marcosvega91**
Fix #125 

**What**:

I have added template for every issues

**Why**:

We need them to mantain the project better

**How**:

Adding some .md files in .github folder

**Checklist**:

- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by smeijer** [comment]
We should also ask for a link to a playground that reproduces the bug or visualizes the need for improvement. Can be very helpful.

**Comment by marcosvega91** [comment]
What do you think if I add this ?

```
We advice to add a screenshot or a gif to help us to understand the problem better 
and a link to a playground (https://testing-playground.com/) 
with the markup and the query that cause the problem.
```

**Comment by smeijer** [comment]
I don't know. I've never read that generic comment block before on one of the testing-lib repos. This is the first time I did that :astonished:.

How about extending the `bug report` comment to request a image there:

```
## 🐛 Bug Report

<!--
A clear and concise description of what the bug is. 
Please add a gif or screenshot to support your case. 
-->
```

And the playground link under reproduce:

```
## To Reproduce

<!--
Steps to reproduce the behavior. 

Please make step 1 a link to your bugged playground if possible (at
https://testing-playground.com). In case the playground crashes entirely,
please share the state right before that crash and tell us what to do to
make it crash. 
-->

1. ...step1
2. ...step2
3. ...step3
```

What do you think of that?

**Comment by marcosvega91** [comment]
I like yours. I have pushed the two template. Let me know if you have some suggestions

**Comment by smeijer** [comment]
@all-contributors please add @marcosvega91 for doc

**Pull request merged**
