### PR TITLE
Add VSCode Extension to header

### PR DESCRIPTION
**Pull request by aganglada**
**What**:

Added VSCode Extension link to the Header

**Why**:

For VSCode Extension visibility

**Checklist**:

- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by smeijer** [comment]
Merging this PR means that I must provide support for it, and prevent it from breaking. I'm happy to do that, but I'd suggest that we then merge the extension into this repo first. ([like you've suggested before](https://twitter.com/aganglada/status/1361009232041156611?s=20)).

What do you think?

**Comment by aganglada** [comment]
Make sense, I will prepare another PR.

**Comment by aganglada** [comment]
Hey @smeijer, don't you think we should work on the monorepo structure before merging the extension, the extension is written in TS and maybe it will be confusing to see TS and JS dependencies all together on the same package.json.

**Comment by smeijer** [comment]
Makes sense. What do you propose? Can you contribute to improving the structure?

**Comment by aganglada** [comment]
> Makes sense. What do you propose? Can you contribute to improving the structure?

Sure, I will have a look at it.

**Comment by aganglada** [comment]
Closing this until we tackle this https://github.com/testing-library/testing-playground/issues/34

**Pull request closed without merging**
