### PR TITLE
fix: highlight of selected elements

### PR DESCRIPTION
**Pull request by smeijer**
**What**:
Ooops, I killed the persistent highlight in #260. I should add tests :disappointed: 

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by delca85** [comment]
Hi @smeijer !
Is https://develop.testing-playground.com/ always updated with the last merged branches? Because I'd like to test if the new changes affect some other behavior or not.

**Comment by smeijer** [comment]
Hi @delca85!

Yes, `develop.testing-playground.com` is always updated with the last merged branches.

`develop.testing-playground.com` is running the `develop` branch.
`testing-playground.com` is running the `live` branch.

I've just updated the live version as well. So they are now both up-to-date.

Which behavior are you concerned about?

**Comment by delca85** [comment]
Thanks for your reply.

I noticed a weird behavior when the `Auto-run code` mode is disabled.
The `run` button icon is always in refreshing state and I am not able to obtain the updated `Preview` from the new markup.

**Comment by smeijer** [comment]
Is that with a specific markup / query?

**Comment by delca85** [comment]
No, I am using the default one.

**Comment by smeijer** [comment]
Should be fixed now

**Comment by delca85** [comment]
Yes it is!

**Comment by smeijer** [comment]
Thanks :slightly_smiling_face:

**Pull request merged**
