### PR TITLE
feat: add embed modal

### LINKED ISSUE #54: add "share" dialog / mode
The share dialog should allow us to construct the share URL. Let's start with an "embed" preview builder. We currently don't expose any interface to let the user toggle on/off various panes.

I also want to investigate if we can hookup firebase or a hosted Mongo. Preferably a database with a free level. So we can store sessions in a database, and provide a short URL instead of saving state in the URL as we currently do.

### PR DESCRIPTION
**Pull request by smeijer**
**What**:
tp-embed

**Why**:
Because now the user has a way to generate their embed urls.

**How**:
Time, and a coffee or 2.

**Checklist**:

- [ ] Tests
- [x] Ready to be merged
      

---

fixes #54

### CODE REVIEW

**Comment by smeijer** [comment]
Some finishing touches on the UI :heart_eyes: 

image

**Comment by delca85** [comment]
This modal, as well as happened with #241 , solves an issue I found in `develop` environment.
I suppose you are going to publish the next playground version with this too so I will not open any issue about it.

**Comment by smeijer** [comment]
The next playground version, will be identical to `develop.testing-playground.com`. That url always contains all merged branches, which makes it equal to the `develop` branch.

**Comment by delca85** [comment]
So something went wrong (or maybe I am doing wrong) because on `develop` branch I see the `embed` modal while on  https://develop.testing-playground.com/ I keep on seeing the old embed version.

Screenshot 2020-07-05 at 16 09 35

**Comment by smeijer** [comment]
Sounds like the service worker is serving a cached version. Can you try turning the service worker off via devtools > application?

**Comment by delca85** [comment]
I have done it but nothing changes.
The weird thing is that when you merged #245 the `new version` message pops out and now I have the `run` button working (so it doesn't sound a cache problem to me).

**Pull request merged**
