### PR TITLE
revert: "feat: add event filters to event log table (#207)"

### PR DESCRIPTION
**Pull request by smeijer**
**What**:
I need to revert #207 (commit 6c47c1287bc49af0578b290cc13700818dcd5ff4) for the time being.

**Why**:
The changes that were applied, make the event log terribly slow. We need to find a better way later.

**How**:
```shell
git revert 6c47c128
```

**Checklist**:

- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by delca85** [comment]
Have you noticed some principal cause of slowness? I could work on it trying to make some improvements.

**Comment by smeijer** [comment]
Hi @delca85, I'm very sorry for the revert!

I don't really know why it was slow. But it was terribly lagging. Not just a little bit. I'm not sure what's going on though.

I'll try upload a video in a moment.

**Comment by delca85** [comment]
Don't worry, it is not a problem at all!

When I have developed it I haven't noticed this slowness but I am sure it is real right now and revert it has been the perfect choice 😊

Given that, if you agree I would be happy to work on it again.

**Comment by smeijer** [comment]
Yeah, that's fine. If you want to take another shot, that would be great.

Not sure what's better though, try to fix the branch as it was, or to change the approach.

**Comment by delca85** [comment]
Hey @smeijer, when you have some time could you please upload the video you spoke about some comments ago?
Just to make me more aware of the problem! Thanks!

**Comment by delca85** [comment]
What looks like laggy to me happens when:
1. populate table with some events
2. deselect an event type (or name) that is the same type (or name) of any event is viewable in the table at the moment
3. event with the deselected type (or name) disappears from the table and the table shows some rows missing

**Pull request merged**
