### PR TITLE
ci: run cypress

### PR DESCRIPTION
**Pull request by marcosvega91**
**What**: run cypress on CI

**Why**: to be sure that e2e pass

**How**:

**Checklist**:

- [ ] Tests
- [X] Ready to be merged

### CODE REVIEW

**Comment by smeijer** [comment]
@marcosvega91 , do you know why the test runner sometimes fails with `UnhandledPromiseRejectionWarning: Error: inotify_add_watch failed: No space left on device`.

For example: https://github.com/testing-library/testing-playground/runs/1524202360?check_suite_focus=true#step:3:116

**Comment by aganglada** [comment]
https://docs.cypress.io/guides/references/configuration.html#Videos

I think we might need to put `videoUploadOnPasses: false` on the config or not use the `--record` flag at all.

**Comment by smeijer** [comment]
Worth a shot. Can we download videos? Otherwise we might want to disable it entirely.

**Comment by aganglada** [comment]
I don't think we can unless we ssh on the runner right? I'm not sure / don't know a lot about Github actions.
Can you confirm @marcosvega91?

**Comment by marcosvega91** [comment]
yes you can save videos and then you can download it, but we don't have an upload step.

**Pull request merged**
